Updates for JWST Cycle 2 Call for Proposals
spacetelescope/jwst_gtvt pull request #82
Opened 2022-10-31 19:51 UTC by mfixstsci

- Update JWST ephemeris
- Update dates in scripts and tests
- Remove old ephemeris

2022-10-31 21:08 UTC, mfixstsci commented
<img width="1391" alt="Screen Shot 2022-10-31 at 1 58 37 PM" src="https://user-images.githubusercontent.com/13122795/199101062-be93ebeb-5029-446b-a955-eb255e7656eb.png">
<img width="1386" alt="Screen Shot 2022-10-31 at 1 55 31 PM" src="https://user-images.githubusercontent.com/13122795/199101084-17a9bd56-f1be-45c8-8696-8bb6efa967ac.png">
<img width="1385" alt="Screen Shot 2022-10-31 at 1 54 48 PM" src="https://user-images.githubusercontent.com/13122795/199101127-1a98178d-d765-40a9-87fb-d2db6418c202.png">
<img width="1388" alt="Screen Shot 2022-10-31 at 1 53 24 PM" src="https://user-images.githubusercontent.com/13122795/199101142-bd320989-8342-4317-9fce-ab79551e0f94.png">
<img width="1388" alt="Screen Shot 2022-10-31 at 1 49 21 PM" src="https://user-images.githubusercontent.com/13122795/199101164-3a60ec12-aebc-40fc-bd07-7921471562ea.png">

2022-10-31 21:13 UTC, mfixstsci commented
@PatrickOgle here are the changes to the GTVT/MTVT. Attached are figures from the examples listed on the README. For some of the moving target, Horizons may have changed the way you can access those specific designations. I think we remove them from the docs. We have a few working examples of the GTVT and MTVT and can provide a link to other designations in the Horizons database. If you think this is a good idea, I can make those changes in this PR.

2022-11-01 00:25 UTC, bholler requested changes
Small change requested: In bin/jwst_gtvt, the latest date is listed as 2024-10-03 and everywhere else it is 2024-10-02. The latest date in the updated file is 2024-10-03. I also just checked Horizons and the JWST ephemeris now goes out to 2024-10-31.

I'm fine leaving the end date at 2024-10-03 (it includes all of Cycle 2 and part of Cycle 3), but we should be consistent with the latest advertised date.

2022-11-01 17:03 UTC, mfixstsci commented
@bholler thanks for catching that. The GTVT goes up to `n-1` of the rows in the ephemeris. If you try running it with the last date in the ephemeris, it will crash with an index out of range error.

2022-11-01 19:56 UTC, bholler approved these changes
That's what I thought, so changing the end date in bin/jwst_gtvt to 2024-10-02 is the right (and easiest) choice. Looks good now!

2022-11-02 17:34 UTC, PatrickOgle commented
@mfixstsci I will rely on you to select any examples and figures to update in JDox. The existing ones look fine to me, even if they are for an earlier ephemeris and date range..

2022-11-02 17:44 UTC, mfixstsci commented
Thanks @PatrickOgle I think that keeping the package data and figures up-to-date makes sense but if we want to update jdox later, we can do that. I just don't want to cause any confusion with that on the user end which is why I suggested it.

2022-11-03 16:16 UTC, mfixstsci commented
@PatrickOgle @bholler I think this is ready to go if one of you would like to review.

2022-11-04 01:48 UTC, bholler commented
@mfixstsci I downloaded the latest version from your branch and tested multiple use cases and flags. All of them worked as expected. The default dates are correct (2021-12-26 to 2024-10-02) for the plots and are correctly presented in the help text for the jwst_gtvt and jwst_mtvt.

There may be updates to the JWST ephemeris coming within the next month, but they would likely be too late to support a release ahead of the Cycle 2 CfP.

I will next work on updating the GTVT and MTVT JDOX pages and writing short release notes for the 0.3.0 G/MTVT release.

2022-11-07 16:18 UTC, mfixstsci commented
@PatrickOgle Will you potentially have time to review this today? If we want to add the background support by the time the cycle 2 CFP, I would like to have this working version in this week and some time to work on the backgrounds PR this week and next. Thank you!

2022-11-10 15:29 UTC, mfixstsci commented on README.md
> +`$ jwst_mtvt 7`  # Uranus (no windows)
The whole point was to not get data and show the `--smallbody`

2022-11-10 20:24 UTC, mfixstsci commented
@bholler could you please give me a review/approval and then we can merge this in and release it? Thank you!

2022-11-10 20:46 UTC, merged