Updates CHANGES.rst
spacetelescope/jwst_gtvt pull request #88
Opened 2023-06-28 21:06 UTC by mfixstsci

Updating `CHANGES.rst` in preparation for release.

2023-06-28 21:11 UTC, bholler requested changes
First item for v1.0: This is useful information but a little vague. For instance, are there specific items that API users should be aware of?
Second item for v1.0: "astroqury" => "astroquery", "back up" => "back-up"
Third item for v1.0: What does this mean about previous releases? Are there some missing words here?

2023-06-28 21:16 UTC, bholler commented
And one bullet point to add:

- The --v3pa flag is now deprecated in favor of --instrument v3pa

2023-06-29 12:29 UTC, mfixstsci commented
@bholler All changes should be in now!

2023-06-29 15:28 UTC, bholler approved these changes

2023-06-29 16:37 UTC, merged